### ISSUE TITLE
Support for popups

### ISSUE THREAD

**Issue by pvgennip** [mennovanslooten/Scout#3]
Support for popup entering text fields and clicking buttons.

Since Safari does not support the # in a url-encoded password for basic authentication, I need a way to fill out the basic auth popup via scout. Selecting a different browser (i.e. chrome) would also work ;-)

**Comment by mennovanslooten** [comment]
PhantomJS does not have a basic auth popup to interact with. In stead, we can set the basic auth name/password via page object settings:
http://phantomjs.org/api/webpage/property/settings.html

Scout 1.5 supports a new type of action: @ 

```
# Sets basic auth
@userName    my_user_name
@password    my_password

# Settings are only effective when set before 'open'
open         http://abc.xyz
```
