### ISSUE TITLE
Number generator

### ISSUE THREAD

**Issue by pvgennip** [mennovanslooten/Scout#4]
Please add a numeric value (or regex string) generator {{###.##}}, so (random) numeric form values can be submitted.

Another idea is to build in a Math function that uses the output to set a value :-)

**Comment by mennovanslooten** [comment]
The new string generator supports a custom set of characters. A number in the form of ###.## could be generated by `{{3:"0123456789"}}.{{2:"0123456789"}}`

http://mennovanslooten.github.io/Scout/api.html#random_string_generators
